### ISSUE TITLE
怎么让脚本直接开始编译

### ISSUE THREAD

**Issue by taipinghehe** [hackyes/OpenWrt-CI#6]
我把脚本替换成以下这样，但是它没有直接运行编译，请问我该怎么做？还有哪里要改。
```
name: OpenWrt

on:
  push:
    branches: 
      - master
      
 # schedule:
 #   - cron: 0 2 * * *
 # watch:
 #   types: started
```
